ListenAddr = ":8080"
DockerURL = "tcp://127.0.0.1:3375"

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/etc/nginx/nginx.pid"
TemplatePath = "/etc/interlock/nginx.conf.template"
MaxConn = 1024
Port = 80
