listenAddr = ":8080"
dockerURL = "unix:///var/run/docker.sock"

[[extensions]]
name = "haproxy"
configPath = "/etc/haproxy.cfg"
pidPath = "/etc/haproxy.pid"
backendOverrideAddress = "172.17.0.1"
connectTimeout = 10
serverTimeout = 10
clientTimeout = 30
maxConn = 1024
port = 80
syslogAddr = ""
adminUser = "admin"
adminPass = "interlock"
sslCert = ""
sslPort = 443
sslOpts = ""
